emojies = { "person":":person_in_tuxedo:",
            "bowl": ":bowl_with_spoon:",
            "bottle":":bottle_with_popping_cork:",
            "potted plant":":potted_plant:",
            "sink":":potable_water:",
            "book":":open_book:",
            "chair":":chair:",
            "cup":":cup_with_straw:",
            "vase":":jar:",
            "couch":":couch_and_lamp:",
            "umbrella":":closed_umbrella:",
            "car":":racing_car:",
            "laptop":":laptop:",
            "bird":":bird:",
            "handbag":":handbag:",
            "teddy bear":":teddy_bear:"
            }